import { computed } from 'vue'
import { useBoardStore } from '../stores/boards'

export function useLabels(boardRef = null) {
  const boardStore = useBoardStore()

  return computed(() => {
    const b = boardRef || boardStore.currentBoard || {}
    const cardLabel = b.card_label || '群友'
    const cardsLabel = b.cards_label || '群友们'
    const groupLabel = b.group_label || '群'
    const groupsLabel = b.groups_label || '群组'
    const fc = typeof b.field_config === 'object' ? b.field_config : {}
    const appTitle = fc.appTitle || `${cardLabel}记忆助手`

    return {
      cardLabel,
      cardsLabel,
      groupLabel,
      groupsLabel,
      appTitle,
      cardManage: `${cardLabel}管理`,
      groupManage: `${groupLabel}管理`,
      homeTitle: `我认识的${cardsLabel}`,
      homeCount: (n) => `${n} 位${cardLabel}`,
      emptyHome: `还没有添加${cardLabel}`,
      emptyHomeHint: `去后台管理页面添加第一位${cardLabel}吧`,
      homeLogin: '登录',
      myBoards: '我的画板',
      publicBoards: '公开画板',
      noPublicBoards: '该用户暂未公开任何画板',
      recentCards: '最近收录',
      publicCards: '公开卡片',
      boardPrivate: '私密',
      boardPublic: '公开',
      adminButton: '管理后台',
      logoutButton: '退出登录',
      backHome: '返回首页',
      userNotFound: '用户不存在',
      userNotFoundHint: (uid) => `UID「${uid}」没有对应的用户`,
      boardCardStatus: (b) => `${b.cards_label || cardsLabel} · ${b.is_public ? '公开' : '私密'}`,
      boardCardCount: (b) => `${b.cards_count || 0} ${b.cards_label || cardsLabel}`,
      addCard: `+ 添加${cardLabel}`,
      addGroup: `+ 添加${groupLabel}`,
      addCardTitle: `添加${cardLabel}`,
      editCardTitle: `编辑${cardLabel}`,
      addGroupTitle: `添加${groupLabel}`,
      editGroupTitle: `编辑${groupLabel}`,
      searchCard: `搜索${cardLabel}...`,
      searchGroup: `搜索${groupLabel}...`,
      cardNameLabel: `${cardLabel}名称 *`,
      remarkLabel: '备注名',
      signatureLabel: '签名',
      locationLabel: '所在地',
      birthdayLabel: '生日',
      birthdayPlaceholder: '如 01-15',
      avatarLabel: '头像 URL',
      importanceLabel: '重要度 (1-5)',
      importanceNone: '未设置',
      circleTagsLabel: '圈子标签',
      impressionTagsLabel: '印象标签',
      notesLabel: '印象笔记',
      accountManageLabel: '账号管理',
      confirmDeleteCard: `确定删除？这将同时删除该${cardLabel}的所有账号。`,
      confirmDeleteAccount: '确定删除此账号？',
      confirmDeleteGroup: `确定删除此${groupLabel}？`,
      confirmDeleteSimple: '确定删除？',
      noData: `暂无${cardLabel}`,
      noAccounts: '暂无账号',
      noMembers: '暂无成员',
      tableCard: cardLabel,
      tableAccounts: '账号',
      tableTags: '标签',
      tableImportance: '重要度',
      tableActions: '操作',
      tableGroupName: `${groupLabel}名称`,
      tableGroupNumber: `${groupLabel}号`,
      tableGroupRemark: '备注',
      tableGroupTags: '标签',
      memberTitle: '成员',
      selectAccount: '选择账号',
      groupNickname: `${groupLabel}名片`,
      save: '保存',
      confirm: '确定',
      cancel: '取消',
      edit: '编辑',
      delete: '删除',
      loading: '加载中...',
      saveSuccess: '保存成功',
      createSuccess: '创建成功',
      saving: '保存中...',
      tagPlaceholder: '输入后回车添加',
      addTag: '添加',
      remove: '移除',
      personDetailNotFound: `找不到这位${cardLabel}`,
      personDetailNotFoundHint: (name) => `「${name}」不存在或已被设置为私密`,
      personDetailAccounts: '账号',
      personDetailMeetings: '相遇记录',
      personDetailRelations: '关系',
      defaultBoardName: '默认看板',
      defaultBoardIcon: '👥',
      newBoard: '+ 新建画板',
      boardNamePlaceholder: '画板名称',
    }
  })
}
